### ISSUE TITLE
Zhuyin annotation formatting 

### ISSUE THREAD

**Issue by supercontingency** [chinese-words-separator/chinese-words-separator.github.io#16]
Traditionally Zhuyin is annotated on the right of the Hanzi character and the tone is written on the right of the Zhuyin like this

![Screenshot 2023-03-16 4 49 56 PM](https://user-images.githubusercontent.com/126799699/225750365-42490ac9-cc28-4383-8156-096c3b532802.png)

I used to think there is a technical limitation that prevents this to be done on browsers but recently I was surprised to find out that there is another chrome extension (Zhuyin) that actually do this and not as an image. 

![image](https://user-images.githubusercontent.com/126799699/225751140-bdafcc37-47e2-4f26-aea6-a658b4d9c340.png)

this certainly makes it more readable for people who use Zhuyin. Could this be implemented for CWS as well?

**Comment by chinese-words-separator** [comment]
Yes there are plenty of technical limitations that prevents it from being implemented like that

And also, the Zhuyin chrome extension does it by simply substituting a font with **a** zhuyin directly embedded in it, which produces annotation that maps to **one** pronunciation only regardless of context, e.g.,

![image](https://user-images.githubusercontent.com/91402471/225763922-5ec1a19a-8e35-49d5-8943-43b53d4a4ad9.png)

On CWS, the annotation it produces for a hanzi depends on the word(can be multi-hanzi) the hanzi is adjacent to or belongs to

行吧 = ㄒㄧㄥˊㄅㄚ˙
银行 = ㄧㄣˊㄏㄤˊ

On Zhuyin chrome extension, both are just (see screenshot):

行吧 = ㄒㄧㄥˊㄅㄚ˙
银行 = ㄧㄣˊㄒㄧㄥ

**Comment by chinese-words-separator** [comment]
Done

The challenge was how to put the tone at the right side of the zhuyin, but it's already possible since two weeks ago, see the tone at the right side of the zhuyin of character 本 on the task [Zhuyin (bopomo) intonations not displayed correctly when text is vertically aligned](https://github.com/chinese-words-separator/chinese-words-separator.github.io/issues/9#issuecomment-1452879797)

I was just not inclined to add another data since I feel it might bloat the page adding another annotation, especially it's on syllable-level. Anyway, a feature is not a bloat if it have enough users and if the machine can handle the processing. I have a 6-year old smartphone, and tested that it can handle the process of adding zhuyin annotation on syllable-level just fine

Example outputs:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/91402471/226165376-0af6160b-bb59-45f0-b29d-ac74330080a5.png">

 
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/91402471/226165523-eef47182-f87f-43df-8388-7d35f5e4c014.png">


<img width="1277" alt="image" src="https://user-images.githubusercontent.com/91402471/226165601-bc0ce333-f5d2-49c8-803a-681a3abc90f3.png">


The feature is on version 8.24.84.1310
