### ISSUE TITLE
Only part of the text is modified

### ISSUE THREAD

**Issue by Drazduf** [chinese-words-separator/chinese-words-separator.github.io#17]
![image](https://user-images.githubusercontent.com/15002249/226214593-98094580-fe4c-414d-9dc5-4b77a543c234.png)

Here only the main content is modified.
Most of the page doesn't seem to be detected by CWS.

**Comment by chinese-words-separator** [comment]
I noticed that too on some sites, made a fix today (uploaded 8.24.84.1320 just now, it should be published within the day)

What is the URL of your site? Need to test if I did not miss anything on the fix

**Comment by Drazduf** [comment]
https://www.msn.com/zh-tw/news/other/我是台灣人-不是中國人-二七部隊長鍾逸人今晚逝世-享嵩壽103歲/ar-AA18OVRe?ocid=Peregrine&cvid=46eb6ee77f1a49ffa70b8fd13a744794&ei=6

**Comment by chinese-words-separator** [comment]
On your URL, I was able to repro the problem on older version of CWS (8.24.84.1311)

![image](https://user-images.githubusercontent.com/91402471/226493734-ac65c335-3570-4313-8c90-e8fae1bf6f98.png)

On latest version (8.24.84.1320), it's ok now

![image](https://user-images.githubusercontent.com/91402471/226493908-cca22262-8a33-4046-8fdf-b665c5e658d3.png)

There are some page that can't be parsed and modified by CWS either due to the Chinese text being rendered on HTML5 canvas, or it is enclosed in [Shadow DOM](https://www.google.com/search?q=shadow+dom). Some web apps use Shadow DOM to componentized some parts of the site, others use it to protect their content

On the URL you provided, some of its headings and titles are componentized with Shadow DOM, hence CWS not being able to parse and modify them. Even other extension dictionaries cannot display definitions on those componentized headings due to those text being enclosed in Shadow DOM

![image](https://user-images.githubusercontent.com/91402471/226494308-302391b5-d23b-4ac7-a362-01c45b23367a.png)

Though CWS cannot parse and modify those Shadow DOM content, it can at least display the dictionary for those text. To do that, highlight the text; then after releasing the mouse button, CWS icon will be shown, then click that icon

![image](https://user-images.githubusercontent.com/91402471/226494638-c8f74b44-ed69-4e46-bbd2-497b6d4517a3.png)

After clicking that icon, the dictionary will be shown:

![image](https://user-images.githubusercontent.com/91402471/226494711-2ecf7f4b-3fe4-4eaf-8b96-c6c48a0ea7f7.png)

The dictionary is not correctly positioned though, due to not Shadow DOM's restrictions, hence its information cannot be parsed, like where its content is positioned in the screen
