### ISSUE TITLE
Zhuyin side display unable to hide annotation for learned words

### ISSUE THREAD

**Issue by supercontingency** [chinese-words-separator/chinese-words-separator.github.io#18]
The new side display of Zhuyin looks great and is much much easier to read. I really think it should be the default way Zhuyin is annotated (make horizontal annotation an option). Thank you so much for making it possible. However I do notice that when I select side annotation of Zhuyin I can not choose to hide annotation for learned words. 

Horizontal Annotation of Zhuyin, hide learned words   

![Screenshot 2023-03-19 9 41 59 PM_2](https://user-images.githubusercontent.com/126799699/226231086-28603689-0af6-4dc4-b320-f61782507319.png)

Learned words are not annotated, nor colored

![Screenshot 2023-03-19 9 56 10 PM_2](https://user-images.githubusercontent.com/126799699/226230993-85d17514-2bd7-46c0-ab50-ee98450bef41.png)

However if I select side annotation of Zhuyin, everything else being the same

![Screenshot 2023-03-19 9 43 45 PM_3](https://user-images.githubusercontent.com/126799699/226230756-a68a42f5-7492-4e2a-b773-004088f77488.png)

now the learned words are not colored, but the annotation remains

![Screenshot 2023-03-19 9 43 32 PM_2](https://user-images.githubusercontent.com/126799699/226231190-f231c91c-3ba8-4fc7-9148-ab6565fa0def.png)

I'm sure this is a easily fixable glitch

**Comment by chinese-words-separator** [comment]
> I'm sure this is a easily fixable glitch

Not a glitch, the mechanism for left/right zhuyin is totally different from under/above zhuyin. The left/right annotation's code barely reused the code of under/above annotation mechanism, especially that the latter is word-based(can be multi-syllables). The left/side annotation is a totally new functionality, I overlooked the `exclude learned` mechanism for left/right zhuyin. Anyway, made the necessary changes so that exclude learned works on left/right zhuyin too, it's on 8.24.84.1320

>  I really think it should be the default way Zhuyin is annotated (make horizontal annotation an option)

No need to make left/right the default when choosing Zhuyin, it's a confusing UX as it breaks symmetry. Besides, Safari has a bug that renders complex layout totally wrong, e.g., when choosing to display the left/right zhuyin on vertical writing system

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/91402471/226268901-2c72e9a8-a51e-45f7-b2d5-93c9c2e3a571.png">

I don't want Safari users to be welcomed by that atrocity when they chosen Zhuyin as a Guide. Safari is really the new IE

If the Under/Above is the default regardless of chosen Guide..

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/91402471/226269614-b2fe15fb-b0ff-4f4e-9d51-ffad3f2100b6.png">


..then Safari users still have usable left/right (under/above technically) Zhuyin functionality when they use CWS on vertical writing system

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/91402471/226269583-078d4ee6-1199-453d-bce3-8e43d5c1c0f6.png">
