### ISSUE TITLE
How to preserve learned words list across updates

### ISSUE THREAD

**Issue by supercontingency** [chinese-words-separator/chinese-words-separator.github.io#19]
I love it that improvements are constantly being made CWS and there are frequent updates. But I find that the only way to transfer the learned words to a new update is to export the list and then manually find each word and click on the text so that it won't be annotated. This is tedious as my daughters learned words list is constantly expanding. Is there a better way?

**Comment by chinese-words-separator** [comment]
Learned words should not get deleted on each update. By any chance, are you deleting Chinese words separator and then re-adding it from Chrome Web Store on each CWS update?

No need to delete it, you can either wait for update to happen automatically (not sure how immediate Google rolls out the update to users), or you go to extensions page to manually force the immediate update. Ellipsis button > More Tools > Extensions. Then you'll see this

![image](https://user-images.githubusercontent.com/91402471/226474736-43278981-4636-4728-8a0c-95015c59c5ff.png)

Hmm.. I guess you are deleting it on each update due to Update button not being available by default. To enable the Update button, toggle the Developer switch, it's off by default

![image](https://user-images.githubusercontent.com/91402471/226474899-d17259e6-d879-4706-8090-d7a243af6a95.png)

Maybe you can manually force Chrome to update extensions even without enabling the Developer mode (and clicking the Update button) by restarting Chrome? Chrome also update extensions in the background automatically if Chrome is idle, that is while you are not using Chrome

"If your question is why it is not auto updating. This typically happens once in several hours. The precise frequency is unknown as mentioned in [developer.chrome.com/extensions/autoupdate](https://developer.chrome.com/extensions/autoupdate). And in practice I've actually had to restart to see it update or ended up updating them manually." -- https://stackoverflow.com/questions/24100507/how-often-do-chrome-extensions-automatically-update#:~:text=This%20typically%20happens%20once%20in,ended%20up%20updating%20them%20manually.&text=The%20new%20version%20appears%20in%20the%20store.


https://www.plusdocs.com/blog/how-to-manually-update-chrome-extensions#:~:text=By%20default%2C%20your%20browser%20will,an%20extension%20you%20have%20installed.

**Comment by chinese-words-separator** [comment]
ChatGPT is hallucinating answers, or it is spewing out old information :)

![image](https://user-images.githubusercontent.com/91402471/226497510-abbd699b-017f-4502-9e5a-f8ea25a8da95.png)
