### ISSUE TITLE
Open source the extension

### ISSUE THREAD

**Issue by srghma** [chinese-words-separator/chinese-words-separator.github.io#8]

**Comment by chinese-words-separator** [comment]
Will not open source the extension, it's a [commercial product](https://apps.apple.com/us/app/chinese-words-separator/id1598790017) now, it will be unfair to contributors if they contribute something significantly and they get nothing in return from their work

Anyway, I'm responsive to feature requests, that's why it goes up to version 8 in just less than two years, due to numerous features requests (some are requested via emails). If I did not lock in the version number to 8.24.84, the product might now be on version 20 or [higher](https://chinese-words-separator.github.io/versions.html). That's also another reason I need to keep control of the software, so I can have a control on version number, 8.24.84 is a birthday. Will be releasing softwares that pertains to my family's birthdays :D

Thanks for understanding, happy language learning 加油！
